name: DCO

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  dco:
    name: DCO Sign-off
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check commit sign-offs
        uses: christophebedard/dco-check@7b0205d25ead0f898e0b706b58227dd5fa7e3f55 # 0.5.0
        with:
          python-version: '3.12'
          args: '--verbose --exclude-emails dependabot[bot]@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
