name: SLSA Provenance

on:
  workflow_call:
    inputs:
      base64-subjects:
        description: Base64-encoded sha256sum-compatible final artifact subjects
        required: true
        type: string

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  provenance:
    name: Generate SLSA Provenance
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0
    with:
      base64-subjects: ${{ inputs.base64-subjects }}
      provenance-name: release.intoto.jsonl
      upload-assets: true
